# Matrix0 V2 Production Configuration
# Optimized for performance and strong play

model:
  # V2 Architecture Features
  planes: 19                       # Input planes for chess board
  channels: 320                    # Number of channels in residual blocks (32M model)
  blocks: 24                       # Number of residual blocks (32M model)
  attention: true                  # Enable attention mechanisms
  attention_heads: 20              # Number of attention heads (32M model)
  policy_size: 4672                # Policy output size
  norm: "group"                    # GroupNorm instead of BatchNorm
  activation: "silu"               # SiLU activation instead of ReLU
  preact: true                     # Pre-activation residual blocks
  droppath: 0.0                    # Temporarily disable DropPath to avoid MPS tiny alloc OOMs
  policy_factor_rank: 128          # Factorized policy head (32M model)
  aux_policy_from_square: true     # Auxiliary from-square prediction
  aux_policy_move_type: true       # Auxiliary move-type prediction
  ssl_curriculum: true             # Self-supervised learning curriculum
  self_supervised: true            # Enable SSL
  ssl_tasks: ["piece", "threat", "pin", "fork", "control"]
  ssrl_tasks: []                   # Keep SSRL off for now (optional)

selfplay:
  num_workers: 3                   # Default worker count
  batch_size: 256                  # Increased from 128 for better efficiency
  shared_inference_batch_size: 48  # Cap shared inference micro-batch (avoid oversized buffers)
  max_games: 420                    # TEST RUN: 20 games total
  max_game_len: 180                # Encourage decisive results
  min_resign_plies: 40             # Allow resigned games slightly earlier
  resign_threshold: -0.70          # Encourage decisive results
  opening_random_plies: 8          # Randomize first N plies to reduce draws
  num_simulations: 200             # Increased from 160 for better quality
  draw:
    min_plies: 50                  # Require more play before draw checks
    window: 12                     # Narrower window
    min_unique: 6                  # Allow faster detection of repetition
    halfmove_cap: 100              # FIDE fifty-move close but more tolerant

training:
  batch_size: 96                   # Stable baseline
  epochs: 2                        # Two epochs per cycle for deeper passes
  learning_rate: 0.001
  weight_decay: 0.0001
  checkpoint_dir: "checkpoints"    # Directory for checkpoints
  checkpoint: "checkpoints/best.pt"   # Always initialize from current best per cycle
  accum_steps: 2                   # Effective batch 192
  progress_interval: 100           # Reduce per-step logging overhead
  grad_clip_norm: 0.5              # Stable
  ssl_weight: 0.15                 # SSL learning contribution
  ssl_warmup_steps: 1000           # Faster warmup for SSL integration
  ssl_every_n: 1                   # Compute SSL every step for consistent learning
  ssl_chunk_size: 128              # Larger chunks for better efficiency
  ssl_target_weight: 1.0           # Normalize SSL magnitude
  # CRITICAL FIX: Force external data usage
  data_mode: "mixed"               # Use mixed mode to access external data
  dataloader_workers: 6            # Increase worker threads for faster data loading
  prefetch_factor: 2               # Maintain prefetching
  ssl_piece_weight: 1.0            # Weight for piece recognition
  ssl_threat_weight: 0.8           # Weight for threat detection
  ssl_pin_weight: 0.7              # Weight for pin detection
  ssl_fork_weight: 0.6             # Weight for fork detection
  ssl_control_weight: 0.5          # Weight for square control
  # removed duplicate ssl_chunk_size key
  precision: "fp16"                # Optimized mixed precision
  use_amp: true                    # AMP
  warmup_steps: 500                # Longer warmup for extended steps
  memory_limit_gb: 14              # MPS limit
  gradient_checkpointing_strategy: "adaptive"    # Enable only if memory is high
  steps_per_epoch: 6000            # Shorter sanity runs per cycle
  use_curriculum: true
  curriculum_phases:
    - { name: openings, steps: 1200, description: "Bootstrap with openings-heavy data" }
    - { name: tactics,  steps: 3600, description: "Emphasize tactical calculation" }
    - { name: mixed,    steps: 7600, description: "Blend external + self-play" }
  policy_masking: true             # Smart masking
  policy_label_smoothing: 0.05     # Mild label smoothing for policy CE
  value_loss: "huber"              # Robust value regression
  huber_delta: 1.0                 # Huber threshold
  extra_replay_dirs:
    - data/stockfish_games        # Curated Stockfish datasets (tagged)
    - data/tactical               # Processed tactical NPZ bundle
    - data/openings               # Processed openings NPZ bundle
    - data/teacher_games          # Teacher-guided replay data

orchestrator:
  initial_games: 210               # 3 workers × 70 games (more self-play data per cycle)
  subsequent_games: 420            # 3 workers × 140 games for stronger data growth
  games_per_cycle: 420             # Total games per cycle
  train_epochs_per_cycle: 1        # One epoch per cycle
  eval_games_per_cycle: 20         # More games per cycle for robust eval
  keep_top_k: 1                    # Keep only best model
  continuous_mode: true            # Continuous cycles enabled
  # Use latest best checkpoint automatically (no override)
  # checkpoint_override: best.pt
  tui: "table"                     # Use table display mode
  ui:
    compact: true                  # Child processes log to files; console stays clean

# Endgame tablebases (Syzygy) for self-play adjudication and correctness
tablebases:
  enabled: true
  path: "data/syzygy"            # Place 3-5 man Syzygy tables here (wdl/)
  max_pieces: 5                   # Match currently installed tables to avoid missing-probe warnings

eval:
  games: 20                        # Expanded evaluation sample per cycle
  max_moves: 180                   # Allow decisive finishes before adjudication
  external_engines: ["stockfish"]  # Compare against Stockfish
  tournament_rounds: 4             # More tournament rounds
  strength_estimation_games: 4     # More strength estimation games
  openings_pgn: "data/openings/main_eval_book.pgn"  # Optional PGN book for varied starts

engines:
  stockfish:
    parameters:
      Threads: 2
      Hash: 256
      MultiPV: 1
    time_control: 100ms
  matrix0:
    type: internal

mcts:
  num_threads: 3                    # Match worker count for optimal MPS performance
  num_simulations: 200              # Increased from 96 for better accuracy
  cpuct: 2.2                      # Restore original exploration level
  cpuct_start: 2.8                  # Restore original early exploration
  cpuct_end: 1.8                    # Restore original late exploitation
  cpuct_plies: 40                   # Restore original schedule length
  cpuct_c_base: 19652
  cpuct_c_init: 1.25
  dirichlet_alpha: 0.3
  dirichlet_frac: 0.25
  dirichlet_plies: 16
  selection_jitter: 0.05
  fpu: 0.2
  fpu_reduction: 0.15
  draw_penalty: -0.5
  tt_capacity: 2000000             # Increased from 1M to 2M for better hit rates (conservative)
  tt_cleanup_frequency: 750         # Reduced cleanup frequency to maintain more entries
  tt_memory_limit_mb: 1024
  batch_size: 24                    # Increased from 16 to 24 for better MPS utilization
  encoder_cache: true
  legal_softmax: true               # Softmax over legal moves only for priors
  max_children: 0                   # Restore unlimited branching for full exploration
  min_child_prior: 0.0              # Restore original prior threshold
  no_instant_backtrack: true
  parent_q_init: true
  tt_cleanup_interval_s: 5
  value_from_white: true            # Use side-to-move value consistently
  virtual_loss: 2.0                 # Restore original virtual loss level
  enable_memory_cleanup: true
  # Throughput optimizations
  simulation_batch_size: 24         # Match batch_size for consistent processing
  parallel_simulations: true        # Enable parallel simulation processing
  tree_parallelism: true           # Enable tree-level parallelism
  memory_cleanup_threshold_mb: 512
  max_tree_nodes: 70000
  playout_random_frac: 0.15         # Conservative randomization for diversity
  enable_entropy_noise: true

presets:
  mps:
    device: "mps"
    num_threads: 3  # Match default worker count
    inference_batch_size: 32
    mcts_threads: 3  # Match default worker count
    worker_threads: 1  # 1 core per worker (3 workers)
