model:
  planes: 19
  channels: 320
  blocks: 24
  attention: true
  attention_heads: 20
  policy_size: 4672
  norm: group
  activation: silu
  value_activation: silu
  preact: true
  droppath: 0.0
  policy_factor_rank: 128
  aux_policy_from_square: true
  aux_policy_move_type: true
  ssl_curriculum: true
  self_supervised: true
  ssl_tasks:
  - piece
  - threat
  - pin
  - fork
  - control
  ssrl_tasks: []
selfplay:
  num_workers: 3
  batch_size: 256
  shared_inference_batch_size: 48
  max_games: 30
  max_game_len: 180
  min_resign_plies: 40
  resign_threshold: -0.7
  opening_random_plies: 8
  num_simulations: 200
  draw:
    min_plies: 50
    window: 12
    min_unique: 6
    halfmove_cap: 100
training:
  batch_size: 96
  epochs: 1
  learning_rate: 0.001
  weight_decay: 0.0001
  checkpoint_dir: checkpoints
  checkpoint: checkpoints/best.pt
  accum_steps: 2
  progress_interval: 100
  grad_clip_norm: 0.5
  ssl_weight: 0.15
  ssl_warmup_steps: 1000
  ssl_every_n: 1
  ssl_chunk_size: 128
  ssl_target_weight: 1.0
  data_mode: mixed
  dataloader_workers: 6
  prefetch_factor: 2
  ssl_piece_weight: 1.0
  ssl_threat_weight: 0.8
  ssl_pin_weight: 0.7
  ssl_fork_weight: 0.6
  ssl_control_weight: 0.5
  precision: fp16
  use_amp: true
  warmup_steps: 500
  memory_limit_gb: 14
  gradient_checkpointing_strategy: adaptive
  steps_per_epoch: 4000
  use_curriculum: true
  curriculum_phases:
  - name: openings
    steps: 1200
    description: Bootstrap with openings-heavy data
  - name: tactics
    steps: 3600
    description: Emphasize tactical calculation
  - name: mixed
    steps: 7600
    description: Blend external + self-play
  policy_masking: true
  policy_label_smoothing: 0.05
  value_loss: huber
  huber_delta: 1.0
  extra_replay_dirs:
  - data/stockfish_games
  - data/tactical
  - data/openings
  - data/teacher_games
orchestrator:
  initial_games: 30
  subsequent_games: 30
  games_per_cycle: 30
  train_epochs_per_cycle: 1
  eval_games_per_cycle: 20
  keep_top_k: 1
  continuous_mode: true
  tui: table
  ui:
    compact: true
tablebases:
  enabled: true
  path: data/syzygy
  max_pieces: 5
eval:
  games: 20
  max_moves: 180
  external_engines:
  - stockfish
  tournament_rounds: 4
  strength_estimation_games: 4
  openings_pgn: data/openings/main_eval_book.pgn
engines:
  stockfish:
    parameters:
      Threads: 2
      Hash: 256
      MultiPV: 1
    time_control: 100ms
  matrix0:
    type: internal
mcts:
  num_threads: 3
  num_simulations: 200
  cpuct: 2.2
  cpuct_start: 2.8
  cpuct_end: 1.8
  cpuct_plies: 40
  cpuct_c_base: 19652
  cpuct_c_init: 1.25
  dirichlet_alpha: 0.3
  dirichlet_frac: 0.25
  dirichlet_plies: 16
  selection_jitter: 0.05
  fpu: 0.2
  fpu_reduction: 0.15
  draw_penalty: -0.5
  tt_capacity: 2000000
  tt_cleanup_frequency: 750
  tt_memory_limit_mb: 1024
  batch_size: 24
  encoder_cache: true
  legal_softmax: true
  max_children: 0
  min_child_prior: 0.0
  no_instant_backtrack: true
  parent_q_init: true
  tt_cleanup_interval_s: 5
  value_from_white: true
  virtual_loss: 2.0
  enable_memory_cleanup: true
  simulation_batch_size: 24
  parallel_simulations: true
  tree_parallelism: true
  memory_cleanup_threshold_mb: 512
  max_tree_nodes: 70000
  playout_random_frac: 0.15
  enable_entropy_noise: true
presets:
  mps:
    device: mps
    num_threads: 3
    inference_batch_size: 32
    mcts_threads: 3
    worker_threads: 1
