# Matrix0 LC0 Integration Test Configuration
# Focused configuration for testing LC0 integration with Apple Silicon optimizations

name: "Matrix0 LC0 Integration Test"
description: "Test Matrix0 against LC0 with Apple Silicon optimizations"

# Output directory for results
output_dir: "benchmarks/results"

# UCI Engine configurations
engines:
  lc0:
    command: "/opt/homebrew/bin/lc0"
    options:
      Threads: "4"
      NNCacheSize: "2000000"
      MinibatchSize: "32"
      Backend: "metal"  # Apple Silicon Metal optimization
      Blas: "true"      # Enable BLAS acceleration
      CPuct: "1.745000" # Default optimized for LC0
      MaxPrefetch: "32"
      RamLimitMb: "0"   # No RAM limit
      MoveOverheadMs: "200"
      TimeManager: "legacy"
      MultiPV: "1"
      NodesPerSecondLimit: "0.000000"

# Test scenarios
scenarios:
  - name: "LC0_Fast_Test"
    engine: "lc0"
    model_checkpoint: "checkpoints/v2_base.pt"
    num_games: 5
    time_control: "10+0.1"
    max_moves: 100
    concurrency: 1
    random_openings: true
    opening_plies: 6

  - name: "LC0_Medium_Test"
    engine: "lc0"
    model_checkpoint: "checkpoints/v2_base.pt"
    num_games: 10
    time_control: "30+0.3"
    max_moves: 150
    concurrency: 1
    random_openings: true
    opening_plies: 8

# Performance monitoring configuration
performance:
  track_cpu: true
  track_memory: true
  track_gpu: true
  sample_interval: 0.1
  log_system_load: true

# Statistical analysis configuration
statistics:
  confidence_level: 0.95
  min_games_for_stats: 5
  calculate_elo: true
  elo_k_factor: 32
