# Matrix0 Benchmark Configuration
# Example configuration for benchmarking Matrix0 against UCI engines

name: "Matrix0 Standard Benchmark"
description: "Standard benchmark suite against Stockfish and lc0"

# Output directory for results
output_dir: "benchmarks/results"

# UCI Engine configurations
engines:
  stockfish:
    command: "/opt/homebrew/bin/stockfish"
    options:
      Threads: "2"
      Hash: "256"
      Skill Level: "0"

  lc0:
    command: "/opt/homebrew/bin/lc0"
    options:
      Threads: "4"
      NNCacheSize: "2000000"
      MinibatchSize: "32"
      Backend: "metal"  # Apple Silicon Metal optimization
      Blas: "true"      # Enable BLAS acceleration
      CPuct: "1.745000" # Default optimized for LC0
      MaxPrefetch: "32"
      RamLimitMb: "0"   # No RAM limit
      MoveOverheadMs: "200"
      TimeManager: "legacy"
      MultiPV: "1"

  komodo:
    command: "komodo"
    working_dir: "/path/to/komodo"
    options:
      Threads: "4"
      Hash: "512"

# Test scenarios
scenarios:
  - name: "Stockfish_Quick_Test"
    engine: "stockfish"
    model_checkpoint: "checkpoints/best.pt"
    num_games: 10
    time_control: "5+0.05"
    max_moves: 200
    concurrency: 2
    random_openings: true
    opening_plies: 8

# Removed lc0 and Komodo scenarios for quick testing

# Performance monitoring configuration
performance:
  track_cpu: true
  track_memory: true
  track_gpu: true
  sample_interval: 0.1
  log_system_load: true

# Statistical analysis configuration
statistics:
  confidence_level: 0.95
  min_games_for_stats: 30
  calculate_elo: true
  elo_k_factor: 32
